version: '3'

networks:
  demo:

services:
  postgres:
    image: postgres:14.3
    container_name: postgres
    volumes:
      - "${PWD}/db_data:/var/lib/postgresql/data"
    restart: always
    ports:
      - 5432:5432
    networks:
      - demo
    environment:      
#      TZ: Europe/Amsterdam
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_DB: demo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root_pass

  postgres-init:
    image: postgres:14.3
    container_name: postgres-init
    volumes:
      - "${PWD}/db_init/:/db_init/"
    networks:
      - demo    
    command: "bash -c 'echo Waiting for Postgres... && \
              cd /db_init && \
              ./db-wait.sh postgres 5432 && \
              cd /db_init/skel-user && \
              echo Initializing skel-user... && \
              /db_init/db-create.sh && \
              echo skel-user: OK && \
              exit 0'"

  skel-user:
    image: syspulse/skel-user:latest
    container_name: skel-user
    depends_on:
      - postgres
      - postgres-init
    restart: always
    ports:
      - 8081:8080
    networks:
      - demo
    command: server
    environment:
      JAVA_OPTS: -Dgod
      DATASTORE: postgres

  skel-notify:
    image: syspulse/skel-notify:latest
    container_name: skel-notify
    restart: always
    ports:
      - 8082:8080
    networks:
      - demo
    command: server
    environment:
      JAVA_OPTS: -Dgod
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${SMTP_FROM}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCOUNT: ${AWS_ACCOUNT}

  skel-enroll:
    image: syspulse/skel-enroll:latest
    container_name: skel-enroll
    restart: always
    volumes:
      - "${PWD}/auth:/auth"
    ports:
      - 8083:8080
    networks:
      - demo
    command: server
    environment:
      JAVA_OPTS: -Dgod
      USER_URI: http://skel-user:8080/api/v1/user
      NOTIFY_URI: http://skel-notify:8080/api/v1/notify
      NOTIFY_EMAIL: ${NOTIFY_EMAIL}
      CONFIRM_URI: http://demo.hacken.cloud
      JWT_ROLE_SERVICE: file:///auth/ACCESS_TOKEN_SERVICE

  # skel-tag:
  #   image: syspulse/skel-tag:latest
  #   container_name: skel-tag
  #   restart: always
  #   volumes:
  #     - "${PWD}/tags:/data"
  #   ports:
  #     - 8084:8080
  #   networks:
  #     - demo
  #   command: server
  #   environment:
  #     JAVA_OPTS: -Dgod
  #     #DATASTORE: dir:///data
  #     DATASTORE: resources://

  skel-auth:
    image: syspulse/skel-auth:latest
    container_name: skel-auth
    restart: always
    ports:
      - 8080:8080
    networks:
      - demo
    command: server
    environment:
      JAVA_OPTS: -Dgod
      USER_URI: http://skel-user:8080/api/v1/user
      GOOGLE_AUTH_CLIENT_ID: ${GOOGLE_AUTH_CLIENT_ID}
      GOOGLE_AUTH_CLIENT_SECRET: ${GOOGLE_AUTH_CLIENT_SECRET}
      TWITTER_AUTH_CLIENT_ID: ${TWITTER_AUTH_CLIENT_ID}
      TWITTER_AUTH_CLIENT_SECRET: ${TWITTER_AUTH_CLIENT_SECRET}
      ETH_AUTH_CLIENT_ID: ${ETH_AUTH_CLIENT_ID}
      ETH_AUTH_CLIENT_SECRET: ${ETH_AUTH_CLIENT_SECRET}


  haas-token:
    image: 649502643044.dkr.ecr.eu-west-1.amazonaws.com/syspulse/haas-token:latest
    container_name: haas-token
    restart: always
    volumes:
      - "${PWD}/tokens/data100:/data"
    ports:
      - 8091:8080
    networks:
      - demo
    command: server
    environment:
      JAVA_OPTS: -Dgod
      #DATASTORE: dir:///data
      DATASTORE: resources://

  haas-circ:
    privileged: true
    image: 649502643044.dkr.ecr.eu-west-1.amazonaws.com/syspulse/haas-circ:latest
    container_name: haas-circ
    restart: always
    ports:
      - 8092:8080
    volumes:
      - "${PWD}/auth:/auth"
    networks:
      - demo
    command: server
    environment:
      JAVA_OPTS: -Dgod
      S3_BUCKET: ${S3_BUCKET}
      DATASTORE: dir:///mnt/s3/data/dev/ethereum/token/
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCOUNT: ${AWS_ACCOUNT}
      JWT_ROLE_SERVICE: file:///auth/ACCESS_TOKEN_SERVICE

  haas-intercept:
    image: 649502643044.dkr.ecr.eu-west-1.amazonaws.com/syspulse/haas-intercept:latest
    container_name: haas-intercept
    restart: always
    volumes:
      # - "${PWD}/scripts:/scripts"
      - "${PWD}/store:/store"
      - "${PWD}/auth:/auth"
    ports:
      - 8093:8080
    networks:
      - demo
    command: server
    environment:
      JAVA_OPTS: -Dgod      
      FEED_TX: kafka://broker-1.hacken.dev:9092/transactions/intercept/latest
      FEED_BLOCK: kafka://broker-1.hacken.dev:9092/blocks/intercept/latest
      FEED_TOKEN: kafka://broker-1.hacken.dev:9092/token_transfers/intercept/latest
      FEED_EVENT: kafka://broker-1.hacken.dev:9092/logs/intercept/latest
      #DATASTORE: mem://
      DATASTORE: dir:///store/intercept
      STORE_SCRIPT: dir:///store/script
      STORE_ABI: dir:///store/abi
      STORE_EVENT: dir:///store/event
      STORE_FUNC: dir:///store/func
      # this is temporary, must be replace with NotificationService URI
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${SMTP_FROM}
      JWT_ROLE_SERVICE: file:///auth/ACCESS_TOKEN_SERVICE

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - skel-auth
      - skel-user
      - skel-notify
      - skel-enroll
      # - skel-tag
      - haas-token
      - haas-circ
      - haas-intercept
      - sparkmagic
    restart: always
    volumes:
      - "${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - 80:80
    networks:
      - demo

  sparkmagic:
    image: 649502643044.dkr.ecr.eu-west-1.amazonaws.com/syspulse/sparkmagic:latest
    container_name: sparkmagic
    restart: always
    volumes:
      - "${PWD}/notebooks:/home/jovyan/work"      
    ports:
      - 8888:8888
    networks:
      - demo
    environment:
      EVN: ${ENV}
