version: '3'

networks:
  demo:

services:

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - sparkmagic
    restart: always
    volumes:
      - "${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - 80:80
    networks:
      - demo

  sparkmagic:
    image: 649502643044.dkr.ecr.eu-west-1.amazonaws.com/syspulse/sparkmagic:latest
    container_name: sparkmagic
    restart: always
    volumes:
      - "${PWD}/notebooks:/home/jovyan/work"
    ports:
      - 8888:8888
    networks:
      - demo
#    environment:
#      ENV: ${ENV}
