import { THash } from "../models/general";

export interface ICategory {
  key: string;
  value: string;
}

export const tokenCategories = [
  { value: "All Categories", key: "all" },
  { value: "Aave Tokens", key: "aave-tokens" },
  { value: "Algorand Ecosystem", key: "algorand-ecosystem" },
  { value: "Analytics", key: "analytics" },
  { value: "Arbitrum Ecosystem", key: "arbitrum-ecosystem" },
  { value: "Arbitrum Nova Ecosystem", key: "arbitrum-nova-ecosystem" },
  { value: "Asset-backed Tokens", key: "asset-backed-tokens" },
  { value: "Automated Market Maker (AMM)", key: "automated-market-maker-amm" },
  { value: "Avalanche Ecosystem", key: "avalanche-ecosystem" },
  { value: "BNB Chain Ecosystem", key: "bnb-chain-ecosystem" },
  { value: "Cardano Ecosystem", key: "cardano-ecosystem" },
  { value: "Celo Ecosystem", key: "celo-ecosystem" },
  { value: "Centralized Exchange (CEX)", key: "centralized-exchange-cex" },
  { value: "Cosmos Ecosystem", key: "cosmos-ecosystem" },
  { value: "Cronos Ecosystem", key: "cronos-ecosystem" },
  { value: "Cryptocurrency", key: "cryptocurrency" },
  { value: "DaoMaker Ecosystem", key: "daomaker-ecosystem" },
  { value: "DeFi Index", key: "defi-index" },
  { value: "Decentralized Exchange (DEX)", key: "decentralized-exchange-dex" },
  { value: "Decentralized Finance (DeFi)", key: "decentralized-finance-defi" },
  { value: "Derivatives", key: "derivatives" },
  { value: "Elrond Ecosystem", key: "elrond-ecosystem" },
  { value: "Eth 2.0 Staking", key: "eth-20-staking" },
  { value: "Ethereum Ecosystem", key: "ethereum-ecosystem" },
  { value: "Exchange-based Tokens", key: "exchange-based-tokens" },
  { value: "Fan Token", key: "fan-token" },
  { value: "Fantom Ecosystem", key: "fantom-ecosystem" },
  { value: "Farming-as-a-Service (FaaS)", key: "farming-as-a-service-faas" },
  { value: "Finance / Banking", key: "finance-banking" },
  { value: "Gambling", key: "gambling" },
  { value: "Gaming (GameFi)", key: "gaming-gamefi" },
  { value: "Gnosis Chain Ecosystem", key: "gnosis-chain-ecosystem" },
  { value: "Governance", key: "governance" },
  { value: "Guild and Scholarship", key: "guild-and-scholarship" },
  { value: "HECO Chain Ecosystem", key: "heco-chain-ecosystem" },
  { value: "Harmony Ecosystem", key: "harmony-ecosystem" },
  { value: "Insurance", key: "insurance" },
  { value: "Internet of Things (IOT)", key: "internet-of-things-iot" },
  { value: "IoTeX Ecosystem", key: "iotex-ecosystem" },
  { value: "KardiaChain Ecosystem", key: "kardiachain-ecosystem" },
  { value: "Kommunitas Launchpad", key: "kommunitas-launchpad" },
  { value: "Lending/Borrowing", key: "lendingborrowing" },
  { value: "Liquid Staking Tokens", key: "liquid-staking-tokens" },
  { value: "MEV Protection", key: "mev-protection" },
  { value: "Masternodes", key: "masternodes" },
  { value: "Meme", key: "meme" },
  { value: "Metagovernance", key: "metagovernance" },
  { value: "Metaverse", key: "metaverse" },
  { value: "Metis Ecosystem", key: "metis-ecosystem" },
  { value: "Moonriver Ecosystem", key: "moonriver-ecosystem" },
  { value: "Move To Earn", key: "move-to-earn" },
  { value: "Music", key: "music" },
  { value: "NFT", key: "nft" },
  { value: "Near Protocol Ecosystem", key: "near-protocol-ecosystem" },
  { value: "OEC Ecosystem", key: "oec-ecosystem" },
  { value: "Ohm Fork", key: "ohm-fork" },
  { value: "Olympus Pro", key: "olympus-pro" },
  { value: "Options", key: "options" },
  { value: "Oracle", key: "oracle" },
  { value: "Perpetuals", key: "perpetuals" },
  { value: "Play To Earn", key: "play-to-earn" },
  { value: "Polkadot Ecosystem", key: "polkadot-ecosystem" },
  { value: "Polygon Ecosystem", key: "polygon-ecosystem" },
  { value: "Prediction Markets", key: "prediction-markets" },
  { value: "Privacy Coins", key: "privacy-coins" },
  { value: "Rebase Tokens", key: "rebase-tokens" },
  { value: "Seigniorage", key: "seigniorage" },
  { value: "Smart Contract Platform", key: "smart-contract-platform" },
  { value: "Social Money", key: "social-money" },
  { value: "Solana Ecosystem", key: "solana-ecosystem" },
  { value: "Sports", key: "sports" },
  { value: "Stablecoins", key: "stablecoins" },
  { value: "Storage", key: "storage" },
  { value: "Synthetic Issuer", key: "synthetic-issuer" },
  { value: "Synths", key: "synths" },
  { value: "Terra Ecosystem", key: "terra-ecosystem" },
  { value: "Tezos Ecosystem", key: "tezos-ecosystem" },
  { value: "Tokenized Stock", key: "tokenized-stock" },
  { value: "Tourism", key: "tourism" },
  { value: "Velas Ecosystem", key: "velas-ecosystem" },
  { value: "Wrapped-Tokens", key: "wrapped-tokens" },
  { value: "XDC Ecosystem", key: "xdc-ecosystem" },
  { value: "Yearn Ecosystem", key: "yearn-ecosystem" },
  { value: "Yield Aggregator", key: "yield-aggregator" },
  { value: "Yield Farming", key: "yield-farming" },
  { value: "Zilliqa Ecosystem", key: "zilliqa-ecosystem" },
];

export const tokenCategoriesHash = tokenCategories.reduce((acc: THash<string>, item: ICategory) => {
  acc[item.key] = item.value;
  return acc;
}, {});

export const circulationSupplyCategoryBrakeDown = [
  {
    title: "Black Holes",
    color: "#12151d",
    change: 0,
    value: 0,
    group: "Destroyed",
    nid: 0,
  },
  {
    title: "Hackers",
    color: "#007787",
    change: 0,
    value: 0,
    group: "Danger",
    nid: 1,
  },
  {
    title: "Unsafe",
    color: "#004650",
    change: 0,
    value: 0,
    group: "Danger",
    nid: 2,
  },
  {
    title: "erc20",
    color: "#e5bf00",
    change: 0,
    value: 0,
    group: "Locked",
    nid: 3,
  },
  {
    title: "CEX",
    color: "#005999",
    change: 0,
    value: 0,
    group: "Purchasable",
    nid: 4,
  },
  {
    title: "wrapped",
    color: "#005999",
    change: 0,
    value: 0,
    group: "Purchasable",
    nid: 5,
  },
  {
    title: "Funds",
    color: "#ac1654",
    change: 0,
    value: 0,
    group: "Circulating",
    nid: 6,
  },
  {
    title: "L2 Bridges",
    color: "#6c1437",
    change: 0,
    value: 0,
    group: "Circulating",
    nid: 7,
  },
];

export const labelsConfig = [
  "Black Holes",
  "CEX",
  "Contracts",
  "erc20",
  "Funds",
  "Hackers",
  "L2 Bridges",
  "uniswap-v3-pool",
  "Unsafe",
  "wrapped",
  "DEX"
];
